Update tranzito-rbac to 1.1.5
Tranzito/tranzito_rbac pull request #12
Opened 2022-11-03 20:26 UTC by ahmed-tranzito

2022-11-08 18:54 UTC, sethherr commented on db/migrate/20221107164611_update_roles_user_table.rb
> +    rename_table :roles_users, :user_roles
This migration fails with 

```
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  column "created_at" of relation "user_roles" contains null values
```

2022-11-08 19:41 UTC, ahmed-tranzito commented on db/migrate/20221107164611_update_roles_user_table.rb
> +    rename_table :roles_users, :user_roles
Updated the migrations, this should work now.

2022-11-08 19:52 UTC, sethherr requested changes
Couple requested changes!

2022-11-08 19:52 UTC, sethherr commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +        UserRoles
Should have a space between "User" and "Roles"

2022-11-08 19:52 UTC, sethherr commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +  = render partial: "tranzito_rbac/shared/admin_current_header", locals: {viewing: "Users"}
Should be `viewing: "User Roles"`

2022-11-08 19:52 UTC, sethherr commented on app/views/tranzito_rbac/users/_table.html.haml
> +- unless users.count.zero?
I think if you're including an if zero, there should be an else that renders "no users found" to prevent confusion.

2022-11-08 19:52 UTC, sethherr commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +      %a.nav-link.float-right.dropdown-toggle{href: "#", role: "button", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false", class: (@deleted_records.present? ? "activ
if you wrap this in a `<ul><li class="nav-item">` it will automatically left align and will look better (e.g. when active, will be active)

2022-11-08 19:52 UTC, sethherr commented on lib/tranzito_rbac/version.rb
> +  VERSION = "1.1.6"
I think this is at least a minor version update - we're adding significant functionality

2022-11-08 19:52 UTC, sethherr commented on spec/requests/tranzito_rbac/roles_request_spec.rb
> +        it "should redirect to show page" do
I think I'd prefer if it redirected to edit, and the user_roles list was included on the edit page.

The roles/show is confusing for me and doesn't clearly show what the permissions are (or include the created/updated, etc). Rather than adding a display for that information, we can just use the edit.

The `user_roles` table should be added to the roles/edit - but you can just include the most recent 20, and not have it sortable (but include a link to view the user_roles/index with all the roles)

2022-11-08 19:52 UTC, sethherr commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +      %a.nav-link.float-right.dropdown-toggle{href: "#", role: "button", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false", class: (@deleted_records.present? ? "activ
Also, please do this to the other index page headers.

And in general, try to avoid using floats. We've got flex box now!

2022-11-08 19:52 UTC, sethherr commented on app/views/tranzito_rbac/users/index.html.haml
> += render partial: 'tranzito_rbac/shared/search_field', locals: {request: { path: users_path, source: "User", attribute: "email"} }
Why wrap the locals in a hash?

2022-11-08 19:52 UTC, sethherr commented on app/views/tranzito_rbac/roles/index.html.haml
> +- unless @roles.count.zero?
If there is an if, also should have an else to show that there are none and not just a failure

2022-11-08 20:52 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +        UserRoles
Sure

2022-11-08 20:53 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/users/_table.html.haml
> +- unless users.count.zero?
Ok

2022-11-08 20:53 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +      %a.nav-link.float-right.dropdown-toggle{href: "#", role: "button", "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false", class: (@deleted_records.present? ? "activ
Thanks for the info

2022-11-08 21:04 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/users/index.html.haml
> += render partial: 'tranzito_rbac/shared/search_field', locals: {request: { path: users_path, source: "User", attribute: "email"} }
It looks more promising to use the `request['path']` than the `request_path`. Thats why I replaced the three variables with the name `request_path, request_source, request_attribute` into hash.
If it's not readable enough, I'll update the hash to simple variables.

2022-11-09 12:24 UTC, ahmed-tranzito commented on spec/requests/tranzito_rbac/roles_request_spec.rb
> +        it "should redirect to show page" do
This spec is related to this subtask
> Show view for roles (should render the User table, for all the users with that role)

Before that, we were redirected to the roles edit path. Now according to this subtask, we are showing it the roles show page this way.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110547147/200829010-f9137e4b-4b83-4c86-8a8b-8942033e6148.png">

That's why I have updated the test case as well.

2022-11-09 12:45 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/users/index.html.haml
> += render partial: 'tranzito_rbac/shared/search_field', locals: {request: { path: users_path, source: "User", attribute: "email"} }
I mean, wrapping it into one object makes more sense to me but we can do it this way as well if you want me to update it.
`locals: {path: users_path, source: "User", attribute: "email"} }`

2022-11-09 17:00 UTC, sethherr commented on spec/requests/tranzito_rbac/roles_request_spec.rb
> +        it "should redirect to show page" do
Yeah but, this doesn't show the information about the admin role - the created at etc table at the top or the permissions - which are already shown on the edit page.

Additionally, I think including pagination and search on this page makes it less clear what the page is for.

I'm happy if you want to add the display stuff to the show, but I think you should remove the pagination and search of the user roles (and just show the first 25, with a link to see the rest via the `user_roles` controller).

Or, you could add the user_roles table to the edit page.

Sorry, after I saw this page I realized that it didn't quite solve the problem that I wanted to solve.

2022-11-09 17:01 UTC, sethherr commented on app/views/tranzito_rbac/users/index.html.haml
> += render partial: 'tranzito_rbac/shared/search_field', locals: {request: { path: users_path, source: "User", attribute: "email"} }
Yeah, I'd like it in one object. Thanks!

2022-11-09 19:38 UTC, sethherr requested changes
Looking good! 1 minor change requested.

2022-11-09 19:38 UTC, sethherr commented on app/controllers/tranzito_rbac/user_roles_controller.rb
> +      @time_range_column = "created_at"
I think it should be possible for `@time_range_column` to be `deleted_at`

2022-11-09 19:38 UTC, sethherr commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +  = render partial: "tranzito_rbac/shared/admin_current_header", locals: {viewing: "User Roles"}
There needs to either be something in the `admin_current_header` or included here to display the role, if search_role is present. It should follow the admin_current_header format for `user_subject` (linking to the role, displaying the name, linking to remove, etc)

2022-11-09 19:38 UTC, sethherr commented on spec/dummy/app/views/kaminari/_first_page.html.erb
> +<%# Link to the "First" page
Why are these included now?

2022-11-09 19:48 UTC, ahmed-tranzito commented on app/controllers/tranzito_rbac/user_roles_controller.rb
> +      @time_range_column = "created_at"
It might not work properly, as `deleted_at` will only be present for those records which are soft-deleted otherwise it will be set to Nil.

2022-11-09 19:53 UTC, ahmed-tranzito commented on spec/dummy/app/views/kaminari/_first_page.html.erb
> +<%# Link to the "First" page
I have added the kaminari views to improve the pagination UI.

Before:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/110547147/200927760-abeb64d3-d093-4cf1-89aa-d9d14a7c43d3.png">

After:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/110547147/200927528-cb0d1e03-3317-4957-a76c-f015d5564477.png">

2022-11-09 20:04 UTC, sethherr commented on app/controllers/tranzito_rbac/user_roles_controller.rb
> +      @time_range_column = "created_at"
That's fine! I still think you should be able to

2022-11-09 20:05 UTC, sethherr commented on app/controllers/tranzito_rbac/user_roles_controller.rb
> +      %w[deleted_at created_at user role creator]
`created_at` should be first, because the first item in the array is the default.

2022-11-09 20:05 UTC, sethherr commented on app/controllers/tranzito_rbac/user_roles_controller.rb
> +      when "creator"
If you can't sort by creator, remove it from sortable.

2022-11-09 20:08 UTC, sethherr commented on app/controllers/tranzito_rbac/user_roles_controller.rb
> +        "user_roles.created_at #{direction}"
Nit: rather than have this else, it would be better if you just used interpolation for all the user_roles attributes - e.g. `else "user_roles.#{attribute} #{direction}"`

2022-11-09 20:24 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +  = render partial: "tranzito_rbac/shared/admin_current_header", locals: {viewing: "User Roles"}
I think the `admin_current_header` is not working in the RBAC for now. I will take a look and try to sort it out. As far as the concern with the suggested changes. I'm unable to get your point, can you please explain it?

2022-11-09 20:28 UTC, ahmed-tranzito commented on app/controllers/tranzito_rbac/user_roles_controller.rb
> +        "user_roles.created_at #{direction}"
Sure, I'll update this

2022-11-09 20:55 UTC, sethherr commented on app/views/tranzito_rbac/user_roles/index.html.haml
> +  = render partial: "tranzito_rbac/shared/admin_current_header", locals: {viewing: "User Roles"}
If you include `search_role` in the params, the searched users are only users that match that role - so it's important to display the role that was searched, and add text about the fact that the user roles are only for the searched role, and give a link to remove `search_role` from the params.

`admin_current_header` has this implemented for `user_subject` - I think it makes sense to add selection of the user_subject to the searched roles in the controller,

2022-11-10 16:55 UTC, sethherr requested changes
Couple minor things, but making progress!

2022-11-10 16:55 UTC, sethherr commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +    - elsif role_subject.present?
What if there is a role and a user?

2022-11-10 16:55 UTC, sethherr commented on app/controllers/tranzito_rbac/base_controller.rb
> +      @role_subject = params[:role_id].present? && TranzitoRbac::Role.find_by(id: params[:role_id])
`user_id` is a `DEFAULT_SEARCH_KEY` key for [sortable in tranzito_utils](https://github.com/Tranzito/tranzito_utils/blob/a24e6cf93e10ce6393318327865801a2dce5858b/lib/tranzito_utils/helpers/sortable_helper.rb#L5).

I don't think we should add `role_id` to the additional keys - so the parameter should be `search_role_id` so that it is included in sortable.

2022-11-10 16:55 UTC, sethherr commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +      - if params[:user_id].present?
I think rather than having a separate handler for users that are really deleted (or have weird ID issues), the users/deleted_alert should include this handling.

2022-11-10 17:15 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +    - elsif role_subject.present?
For now, there will be either user_id or role_id. I will update this so it will work for both.

2022-11-10 17:29 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +      - if params[:user_id].present?
Do you mean that we should handle the users which are soft_deleted and the ones who are really deleted both should be handled in the `deleted_alert` partial?

2022-11-10 17:32 UTC, ahmed-tranzito commented on app/controllers/tranzito_rbac/base_controller.rb
> +      @role_subject = params[:role_id].present? && TranzitoRbac::Role.find_by(id: params[:role_id])
So basically we just need to change the param's name from `role_id` to `search_role_id`, right?

2022-11-10 17:33 UTC, sethherr commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +      - if params[:user_id].present?
Yes. The `deleted_alert` partial should handle if `user_id` doesn't match any user. That seems logical?

2022-11-10 17:43 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +      - if params[:user_id].present?
For now `deleted_alert` partial only renders for the users that are soft_deleted. It means the User with that specific ID is present in the DB. On the other side, the users that are really deleted are the ones missing in the DB. I think they both are separate things and should be handled separately as implemented in bikehub.

2022-11-10 17:58 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +      - if params[:user_id].present?
Yeah, it looks fine for now. We should consider this as a future update.

2022-11-10 19:02 UTC, sethherr requested changes
Couple more minor things, sorry!

2022-11-10 19:02 UTC, sethherr commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +    %p
Each option should have a for viewing all link - e.g. if there is a `user_id` present, but no user, you should be able to click a link to "all users" - and if there is a role, you should be able to click a link to view for "all roles"

2022-11-10 19:26 UTC, ahmed-tranzito commented on app/controllers/tranzito_rbac/base_controller.rb
> +      @user_subject = params[:user_id].present? && User.find_by(id: params[:user_id])
Ah, nice catch. Thanks!

2022-11-10 20:24 UTC, ahmed-tranzito commented on app/views/tranzito_rbac/shared/_admin_current_header.html.haml
> +    %p
That's a good suggestion. I'll do it this way.

2022-11-10 22:22 UTC, sethherr approved these changes
👍

2022-11-11 12:18 UTC, merged